#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

use app\core\components\configManager\ConfigManager;
use app\core\components\configManager\ConfigConsole;

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

require(__DIR__ . '/core/vendor/autoload.php');
require(__DIR__ . '/core/vendor/yiisoft/yii2/Yii.php');
// основная конфигурация
$baseConfig = require(__DIR__ . '/core/config/console.php');

// менеджер конфигураций
$config = Yii::createObject([
    'class' => ConfigManager::className(),
    'modulesPath' => Yii::getAlias('@app' . '/modules'),
], [$baseConfig, new ConfigConsole()]);

$application = new yii\console\Application($config->getConfig());
$exitCode = $application->run();
exit($exitCode);
