<?php
/**
 * Class AjaxController
 * @package app\modules\shop\controllers\frontend
 * @author Kirill Golodaev <kirillgolodaev@gmail.com>
 */


namespace app\modules\shop\controllers\frontend;

use app\modules\shop\models\base\Cart;
use app\modules\shop\service\frontend\CartViewService;
use Yii;
use app\modules\shop\components\FrontendController;
use app\modules\shop\service\frontend\CartModelService;

class CartController extends FrontendController
{

    public function actionAdd()
    {
        if ($post = Yii::$app->request->post()) {
            Yii::$app->cart->add($post['productId'], $post['qty']);
        }
    }

    public function actionIndex()
    {
        $modelService = new CartModelService();
        $modelService->setRequestData([
            'post' => Yii::$app->request->post(),
        ]);
        $modelService->actionIndex();

        $viewService = (new CartViewService())->setData($modelService->getData());

        return $this->render('index', ['data' => $viewService]);
    }

    public function actionEdit()
    {
        // your default model and dataProvider generated by gii
        // validate if there is a editable input saved via AJAX
        if (Yii::$app->request->post('hasEditable')) {
            // instantiate your book model for saving
            $bookId = Yii::$app->request->post('editableKey');
            $model = Cart::findOne($bookId);

            // store a default json response as desired by editable
            $out = json_encode(['output' => '', 'message' => '']);

            // fetch the first entry in posted data (there should only be one entry
            // anyway in this array for an editable submission)
            // - $posted is the posted data for Book without any indexes
            // - $post is the converted array for single model validation
            $posted = current($_POST['Cart']);
            $post = ['Cart' => $posted];

            // load model like any single model validation
            if ($model->load($post)) {
                // can save model or do something before saving model
                $model->save();

                // custom output to return to be displayed as the editable grid cell
                // data. Normally this is empty - whereby whatever value is edited by
                // in the input by user is updated automatically.
                $output = '';

                // specific use case where you need to validate a specific
                // editable column posted when you have more than one
                // EditableColumn in the grid view. We evaluate here a
                // check to see if buy_amount was posted for the Book model
               /* if (isset($posted['qty'])) {
                    $output = Yii::$app->formatter->asDecimal($model->qty, 2);
                }*/

                // similarly you can check if the name attribute was posted as well
                // if (isset($posted['name'])) {
                // $output = ''; // process as you need
                // }
                $out = json_encode(['output' => $output, 'message' => '']);
            }
            // return ajax json encoded response and exit
            echo $out;
            return;
        }

    }
}